### PR TITLE
[8pt] PR: fix input pathing

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
When a recent version of ras2catchment.py was checked in, it had hardcoding paths that were not easily testable. Some new input files were also required to get the tool working.  Considering the new data flow model and folder structure, the team agreed to attempt to standardize the pathing from one folder to another.  A new system was added to help manage paths inside the `c:\ras2fim_data` directory, or whatever name you like. 

All of the original arguments and full pathing continues to work, but is no longer needed and it is encourage to now only use the pathing defaults.

For more details and examples, please see the notes in the __main__ function of ras2fim.py.

A new system was added to `ras2fim.py`, `run_ras2rem.py` and `ras2catchments.py` by moving logic out of the __main__ functions. Moving that code into a separate method, allows for input validation, and defaults to be accurately be set even if the .py file is being used without going through command line.  

For example, with run_ras2rem.py, a person can use the script from command line, however, ras2fim.py could also call directly over to a method in run_ras2rem and not come through command line. This can result in key function arguments validation and variable setup to be missed. By moving validation and defaults into a separate function inside run_ras2rem.py, they can be enforced or adjusted.

Some changes were started against ras2catchments.py for new data required for it to be run, but at this point, the ras2catchment system is not working. A separate card will be created to continue to adjust it and get it fully operational. 

Other changes include some styling upgrades were made to be more compliant with PEP-8 and FIM development standards.

Note: While changes to ras2fim.py are difficult to see using standard GIT or VSCode comparison editors, using a side by side comparison tool will make it much easier to see. GIT has showing the changes as split and merging lines all over the place instead of block changes.  While validation and basic ras2fim.py setup logic was moved into a new method, for reasons explained above, AND some variable names were changed to be more explicit, **the core ras2fim processing logic** has not changed. That core logic does not exist in the ras2fim.py file but in various other .py files which barely changed.

PR related to issue [51](https://github.com/NOAA-OWP/ras2fim/issues/51). 

### Additions  
- `src`
    - `shared_variables.py`: holding all of the default pathing, folder and file names to ensure consistency throughout the code.

### Changes  
- `docs`
    - `INSTALL.md`:  Updated for more information about the new default folder structure. More updates are required later as ras2fim.py usage stabilizes.
    - two new image files were added in support of the updates to `INSTALL.md`.
- `src`
    - `calculate_all_terrain_stats.py`: cleanup for redundant info and screen output.
    - `clip_dem_from_shape.py`: cleanup for redundant info and screen output.
    - `conflate_hecras_to_nwm.py`: cleanup for redundant info and screen output and changed some file names to come from shared_variables.
    - `convert_tif_to_ras_hdf5.py`: cleanup for redundant info and screen output.
    - `create_fim_rasters.py`: cleanup for redundant info and screen output and added a "with" wrapper around the processing pooling for stability reasons.
    - `conflate_shapes_from_hecras.py`: cleanup for redundant info and screen output.
    - `get_usgs_dem_from_shape.py`: cleanup for redundant info and screen output.
    - `ras2catchments.py`: Changes described above (pathing, styling, moving code out of the "main" function, adding in pathing for new data sources, etc). Note: the script is not operational but has taken a step forward to getting it fully working. The new data inputs and pathing were required first.
    - `ras2fim.py`:  Many of the changes listed above such as some small styling fixes, moving code out of "main", cleaning pathing to defaults, and added a bit of better "code step" tracking. 
    - `run_ras2rem.py`: Change described above (pathing, using common values from `shared_variables.py`, minor styling fixes, moving logic from "main" to another method, and fixes to be more PEP-8 compliant. Note: This file does not work and did not work in the current dev branch prior to this PR. Assumed that a fix is coming from another PR.
    - `simplify_fim_rasters.py`: cleanup for redundant info and screen output.
- `tools`
    - `convert_ras2fim_to_recurr_validation_datasets.py`:  Changes to support the new common values from `shared_variables.py`
    - `nws_ras2fim_calculate_terrain_stats.py`:  cleanup for redundant info and screen output.
    - `nws_ras2fim_check_processs_stats.py`:  cleanup for redundant info and screen output.
    - `nws_ras2fim_clip_dem_from_shape.py`:  cleanup for redundant info and screen output.
    - `nws_ras2fim_entwine_dem_from_shp.py`: cleanup for redundant info and screen output.

### Testing

- `ras2fim.py` was run a large number of times with various combinations of defaulted pathing and overridden pathing. Note: it would always fail on Step 8 when it calls run_ras2rem.py due to a pre-existing ras2rem bug.
- `ras2catchments.py` was partially tested for pathing but could not be fully tested.
- `run_ras2rem.py` was partially tested for pathing but could not be fully tested.

Examples of tests performed, noting that I made a whole copy of the c:\ras2fim_data folder renaming various folders to validate scenarios.

python ras2fim.py -w 12090301 -o 12090301_meters_2277_test_1 -p EPSG:2277 -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
	- ran just fine.
	- test passed

python ras2fim.py -w 12090301 -i C:\ras2fim_data_22\OWP_ras_models_22\models_22 -o C:\ras2fim_data_22\output_ras2fim_models_22\12090301_meters_2277_test_22 -p EPSG:2277 -n C:\ras2fim_data_22\inputs\X-National_Datasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
     -   sb - error that child folder exists
	- test passed
	
python ras2fim.py -w 12090301 -i C:\ras2fim_data_2222\OWP_ras_models_22\models_22 -o C:\ras2fim_data_22\output_ras2fim_models_22\12090301_meters_2277_test_22 -p EPSG:2277 -n C:\ras2fim_data_22\inputs\X-National_Datasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
	- sb bad -I   
	- test passed

python ras2fim.py -w 12090301 -i C:\ras2fim_data_22\OWP_ras_models_2222\models_22 -o C:\ras2fim_data_22\output_ras2fim_models_22\12090301_meters_2277_test_22 -p EPSG:2277 -n C:\ras2fim_data_22\inputs\X-National_Datasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
	sb bad -I
	test passed
	
python ras2fim.py -w 12090301 -i C:\ras2fim_data_22\OWP_ras_models_22\models_2222 -o C:\ras2fim_data_22\output_ras2fim_models_22\12090301_meters_2277_test_22 -p EPSG:2277 -n C:\ras2fim_data_22\inputs\X-National_Datasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
	sb bad -I
	test passed
	
python ras2fim.py -w 12090301 -i C:\ras2fim_data_22\OWP_ras_models_22\models_22 -o C:\ras2fim_data_22\output_ras2fim_models_2222\12090301_meters_2277_test_22 -p EPSG:2277 -n C:\ras2fim_data_22\inputs\X-National_Datasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
	sb bad -o
	test passed
	
python ras2fim.py -w 12090301 -i C:\ras2fim_data_22\OWP_ras_models_22\models_22 -o C:\ras2fim_data_22\output_ras2fim_models_22\12090301_meters_2277_test_22 -p EPSG:2277 -n C:\ras2fim_data_22\inputs\X-National_Datasets_22 -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
	sb bad -n
	test passed
	
python ras2fim.py -w 12090301 -i C:\ras2fim_data_22\OWP_ras_models_22\models_22 -o C:\ras2fim_data_22\output_ras2fim_models_22\12090301_meters_2277_test_22 -p EPSG:2277 -n C:\ras2fim_data_22\inputs\X-National_Datasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif
	sb good
	test passed
	
------------------

run_ras2rem.py

python run_ras2rem.py -p 12090301_meters_2277_test_1111  (going to default of c:\ras2fim_data\output_ras_models)
	- sb  bad -p  ( folder does not already exists)
	- test passed

python run_ras2rem.py -p C:\ras2fim_data_22\output_ras2fim_models_2222\12090301_meters_2277_test_22
	- sb  bad -p  
	- test passed

python run_ras2rem.py -p 12090301_meters_2277_test_1   (going to default of c:\ras2fim_data\output_ras_models)
	sb good  (folder recreated)
	- test passed
	
python run_ras2rem.py -p C:\ras2fim_data_22\output_ras2fim_models_22\12090301_meters_2277_test_22 
	sb good
	Test passed

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [ ] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/docs/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
@EmilyDeardorff - When this gets merged, you will need to take some steps, see the Changelog.

@AliForghani-NOAA  - Between you and @JamesColl-NOAA : Can one of you guys test the changes to ras2fim,py for both minimal args and overridden args.

@AliForghani-NOAA - I couldn't test run_ras2rem.py as it has a pre-existing bug. Can you fix that bug, then test my new pathing changes? Notice.. your args are a fair bit different now.

@LauraKeys-NOAA - I added pathing fixes, loaded new data sources for catchments, but couldn't quite get it working. I will make a separate card to get it running again with the new input sources and leave this ticket to focus on just pathing. If you decided you want to get this running again, can we talk about some ideas I have?

@BradfordBates-NOAA - Just adding you as a listener.

**Comment by BradfordBates-NOAA** [comment]
Can I merge this?

**Comment by RobHanna-NOAA** [comment]
Not yet. It needs testing. I am going to show Ali this morning how to test it.

**Comment by RobHanna-NOAA** [comment]
I was unable to test run_ras2rem.py earlier as it had a bug. With a temp fix, I am now able to test ras2fim.py and run_ras2rem.py together and it exposed a bug. I am fixing it now and am removing most of the "init_and_run" methods, except for ras2fim.py.  Code update checking is coming.

**Comment by BradfordBates-NOAA** [comment]
Given @AliForghani-NOAA's comment, are we ready to approve and merge this, @RobHanna-NOAA?

**Comment by RobHanna-NOAA** [comment]
Huge thanks Ali for testing this. I know it was a lot of work and headache getting your head around (forgive the pun). Ya, you have a point, maybe removing -bp would be fine. Maybe a bit too much flexibility on that one but it does add confusion. I will do that this morning and let you know when that is done. Shouldn't take long.

**Comment by AliForghani-NOAA** [comment]
There is an issue in the environment. I removed my older ras2fim env and created a new env by:
conda env create -f environment.yml

using the new env I get below error:
image

I tested both "strict EC2" and "Full Freedom" options and both failed at the same location shown above.

**Comment by AliForghani-NOAA** [comment]
Another issue when an output folder already exists...
Assuming when we use Strict EC2 method and we only give output folder name (and not path), and the same folder name already exists in "C:\ras2fim_data\output_ras2fim_models", the code deletes the current output folder and stops.  Basically, there is a danger to remove the results of previous runs. Is this intentional?
Below is what happens if "finaltest" folder already exists in "C:\ras2fim_data\output_ras2fim_models". The finaltest is also got removed. 
image

**Comment by AliForghani-NOAA** [comment]
Regarding the 

> Another issue when an output folder already exists... Assuming when we use Strict EC2 method and we only give output folder name (and not path), and the same folder name already exists in "C:\ras2fim_data\output_ras2fim_models", the code deletes the current output folder and stops. Basically, there is a danger to remove the results of previous runs. Is this intentional? Below is what happens if "finaltest" folder already exists in "C:\ras2fim_data\output_ras2fim_models". The finaltest is also got removed. image

Rob, 
I am not talking about pathing details for this topic--the pathing is fine here. 
And, that's good that if we have a "successful" ras2fim run the current outputs are not deleted if we use the same output name/path. This issue happens when we have a  "partially successful" run, which is ok to be deleted but it would be nice to give a more clear error message and then terminate the code or simply running the code and overwrite the current results.

**Comment by RobHanna-NOAA** [comment]
Yes. I am working on better messaging for that. We won't be removing any folders for users. 

My new message says when in error `raise ValueError('The -o folder final child folder (base path) can not pre-exit as we will create it, but the ' \
                         ' parents folders must exist. See code notes in the __main__ section for details and examples')`

and in main it says:
`    #        - The -o arg is required, but can be either a full path (as shown above), or a simple folder name. 

    #             ie) -o c:/users/my_user/desktop/ras2fim_outputs/12090301_meters_2277_test_2  (the 6 folders of 01, 02... 06 will be under this folder can not be overriden)

    #                 -o 12090301_meters_2277_test_3  (We will use the root default pathing and become c:/ras2fim_data/outputs_ras2fim_models/12090301_meters_2277_test_3)

    #             As before.. if the final folder of 12090301_meters_2277_test_2 can not pre-exist and we will create it.

    #             However, as before, it will error out if the parent path (ie c:/users/my_user/desktop/ras2fim_outputs) does not exist.
`

Is this message better?

**Comment by AliForghani-NOAA** [comment]
> Now that I think of it.. Question: Should we say the parent paths, must already exist, but the child (base_path) can not exist (previous behaviour). OR.. do we say it that we will create the full path if it does not exist? Currently. we don't have an option to allow for "overwritting" the output folder. Thougths?

If we have only those three options (Strict and Liberal EC2, and Full Freedom) without -bp flag, I do not see a case that we have issue for parent paths, because if the user provides full paths, it is the responsibility of the user to make sure the parent path exists.

**Comment by RobHanna-NOAA** [comment]
I am removing -bp so you are definitely correct. Their parent paths have to pre-exist.

**Comment by AliForghani-NOAA** [comment]
With the updated push today, I ran ras2fim with the new env on my personal computer and got error again at Step 3 (although with different error message) as shown below:
image

Switching to original dev and running the same code/arguments will make the run successful.

**Comment by RobHanna-NOAA** [comment]
ya.. that is a problem with the right version of rasterio being loaded.  Let's debug your EC2 tomorrow.

**Comment by RobHanna-NOAA** [comment]
Validated that we do not need the newer rasterio. As such, the environment.yml was rolled back as the change to the conda environment is no longer needed.

**Comment by AliForghani-NOAA** [comment]
@RobHanna-NOAA 
Below is the error message we get when the output path already exists:
image

Can you change the message to something like:
"Output directory already exists. Please choose a different output path (or folder name) or delete the current output folder and try again." Also, can you please make the code to have a cleaner exit.

**Comment by AliForghani-NOAA** [comment]
@RobHanna-NOAA 
Another issue is about using "run_ras2rem.py" independently. As shown below, there is no i flag to specify inputs of ras2rem. 

image

After adding -i flag, please show an example how one should use "run_ras2rem.py" independently on a current ras2fim output folder 5. Below is how I was hoping to make it work for an existing ras2fim output on EC2  
image

**Comment by RobHanna-NOAA** [comment]
> @RobHanna-NOAA Another issue is about using "run_ras2rem.py" independently. As shown below, there is no i flag to specify inputs of ras2rem.
> 
> image
> 
> After adding -i flag, please show an example how one should use "run_ras2rem.py" independently on a current ras2fim output folder 5. Below is how I was hoping to make it work for an existing ras2fim output on EC2 image

Sorry.. we do not want an -i flag.  As documented, the output folder is not to the "06" folder, but it's parent folder that has an "01 to 05 folders in it. So.. the existance of those "01..0"5 is your input folder and we do not want this to be optional. If we do.. we are allowing ourselfs to have an ras2fim outputs in totally different locations than where the "06" folder we be created. They all must be side by side.   So.. no -i input. It is covered as part of the -o flag.

**Comment by AliForghani-NOAA** [comment]
Great, so the problem is only the help notes that are not clear. I think we should avoid using -o because o implies only output. Can we change it to -p (as parent) or something other than o? And please add the note for this flag something like below to make it more clear:

- p: This should be the path to the folder containing the ras2fim 5 output subfolders. The ras2rem result will be created in a folder called "06_rem" in the same parent directory.

**Comment by RobHanna-NOAA** [comment]
oh.. that is a good idea. It is a quick fix for -p. I am on it and will update the PR and code inline notes to try to be more clear. Wordsmithing is something that I am not very good at.

**Comment by RobHanna-NOAA** [comment]
yes.. When you execute "run_ras2rem.py" and the "06" folder exists, it will be deleted and rebuilt.  However.. the "parent" (ras2fim huc directory) should never be deleted or overwritten at this point.  Did I not put this in the PR or notes? I will check.   Would you like to fail if the "06" folder exists?  If you want it to fail, then you will have to delete the "06" folder to re-run.

**Comment by RobHanna-NOAA** [comment]
The problem here is the word "output". Out can mean "outputs_ras2fim_models", or one of its huc folders such as 12090301_meters_2277, but it sounds like you are also using the word outputs to mean the "06" folder?

**Comment by AliForghani-NOAA** [comment]
That's fine as is. Just wanted to make sure the behaviors are as you planned.

**Comment by AliForghani-NOAA** [comment]
> The problem here is the word "output". It can mean "outputs_ras2fim_models", or one of its huc folders such as 12090301_meters_2277, but it sounds like you are also using the word outputs to mean the "06" folder?

In this regard, I meant ras2rem output which is folder 6 only.

**Comment by RobHanna-NOAA** [comment]
> > The problem here is the word "output". It can mean "outputs_ras2fim_models", or one of its huc folders such as 12090301_meters_2277, but it sounds like you are also using the word outputs to mean the "06" folder?
> 
> In this regard, I meant ras2rem output which is folder 6 only.


Ok. I will start using the word "parent" to be the huc folder, and "output" to be the 06 folder. Maybe we should only use the phrases of parent or 06

**Comment by RobHanna-NOAA** [comment]
The notes in the "main" of run_ras2rem.py have a note saying "If the "06" folder exists, it will be removed and overwritten.  I will update that to be "If the "06_ras2rem" folder exists, it will be removed and overwritten." and add more notes above it. I was trying not to add to much detail in the run_ras2rem.py -h (help).  I will ensure it is spelled out better in the PR as well.

**Comment by AliForghani-NOAA** [comment]
> > > The problem here is the word "output". It can mean "outputs_ras2fim_models", or one of its huc folders such as 12090301_meters_2277, but it sounds like you are also using the word outputs to mean the "06" folder?
> > 
> > 
> > In this regard, I meant ras2rem output which is folder 6 only.
> 
> Ok. I will start using the word "parent" to be the huc folder, and "output" to be the 06 folder. Maybe we should only use the phrases of parent or 06

when ras2rem is run independently, it is obvious that output means output of ras2rem, and no reason to be worried that it is being confused with ras2fim outputs.

**Comment by RobHanna-NOAA** [comment]
Ok.. if I understand it correctly, you want the functionality changed so that if the "06_ras2rem" does already exist, then error out and tell them to either remove the 06_ras2rem folder or repoint to a different folder. Correct?

**Comment by AliForghani-NOAA** [comment]
No, to me the current functionality is fine.

**Comment by RobHanna-NOAA** [comment]
PS.  The output for exception and Value Errors are default Python behavior. We can build our own exception system or add a full error logging system, but that has to be done later, due to time constraints.  Output exceptions by default are not pretty, but we can fix it later.

**Comment by RobHanna-NOAA** [comment]
But I can cleanup the error message itself (and will)

**Comment by RobHanna-NOAA** [comment]
Also.. double checking.. ras2catchments also puts files in the "06" folder. When we delete and rebuild that folder, those catchment files will be deleted. But the  normal flow will be to execute ras2fim.py which will do all ras2rem and ras2catchments. Is this ok?

**Comment by AliForghani-NOAA** [comment]
Great, that’s all we need for now.

**Comment by AliForghani-NOAA** [comment]
I am not sure about this topic. Jim or Laura can help more on this.

**Review by AliForghani-NOAA — DISMISSED** [review]

**Comment by AliForghani-NOAA** [comment]
Thanks Rob for the great enhancements.

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
