### PR TITLE
[3pt] PR: New tool: ras_unit_to_s3

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
This PR includes a new tool that can take a ras2fim unit output folder and upload it to S3. During that upload processes, it checks the s3 `output_ras2fim` folder to look for folders already share the same huc and crs values. A folder may/may not pre-exist that matches the huc and crs but may/may not share a date.  A new master file called `ras_output_tracker.csv` exists now in the s3 `output_ras2fim` folder which tracks all folders uploaded, moved to archive, and overwritten. All activities done by the new `ras_unit_to_s3.py` update this new master copy in S3.

The s3 `output_ras2fim` folder is intended to have only folder with a given huc and crs and would almost always be the latest version.  All other versions would be renamed to the phrase of "_BK_" and a date and moved into the `output_ras2fim_archive` folder. 

There are some combinations where a user can overwrite older folders or simply move incoming folder straight to the archive folder.   Lots of output including input question to the user with choices of aborting, moving existing folders and other options.

Other small fixes include:
- [issue 152](https://github.com/NOAA-OWP/ras2fim/issues/152), which changes all ras2fim code to use UTC times.
- [issue 111](https://github.com/NOAA-OWP/ras2fim/issues/111) to fix is to make use of a previously added method which can validate a CRS when it comes in as an input arg to a file. This has now been applied to both `ras2fim.py` and `get_models_by_catalog.py`.
- `get_models_by_catalog.py` was renamed from its previous name of `get_ras_models_by_catalog.py`. It was also adjusted for an additional filter as per change in pre-processing (RRASSLER team).
- change all files with used multi-proc or multi-threading to be cpu proc count - 2 (used to be -1 and it was leaving machines without not enough cpu's to handle other tasks. It was especially noticed when debugging and needed to use Task Manager and it was bogging down the system badly.
- some small misc cleanup on a few files such as a bit of variable and function renaming, output and formatting.

### Additions  
- `tools`
   - `ras_unit_to_s3.py`: As described above.
   - `s3_shared_functions.py`:  A file to manage all communication with S3, upload, deleted, move, etc. It does not yet have a download function but it will likely be added and plugged into `get_models_by_catalog.py` at a later date. However, other tools that are coming soon can use these same functions.

### Changes  
- `pyproject.toml`: Added a few adjustments to the pre-file-ignores section.
- `src`
    - `calculate_all_terrain_stats.py`: Change multi-proc / number of workers count as mentioned above.
    - `conflate_hecras_to_nwm.py`: Change multi-proc / number of workers count as mentioned above.
    - `create_fim_rasters.py`: Change multi-proc / number of workers count as mentioned above.
    - `create_geocurves.py`: Change multi-proc / number of works and changed date time to UTC.
    - `create_shapes_from_hecras.py` Change multi-proc / number of works and comments on non standard linting issue.
    - `ras2catchment.py`: Change multi-proc / number of works and changed date time to UTC.
    - `ras2fim.py`: Changes include: 
         - Renamed a few variables to be more descriptive.
         - Small changes the argument log file.
         - Small change to track each section being processed by ensuring they have the word `step` in the header (not necessarily followed by a number). This allows for easier searching of the screen output for section headers.
         - Change multi-proc / number of works and changed date time to UTC.
     - `reformat_ras_rating_curve.py`: Change multi-proc / number of workers count as mentioned above.
     - `run_ras2rem.py`: Change multi-proc / number of workers count as mentioned above.
     - `shared_functions.py`: Moved the print_date_time_duration location in the file.  Added a test that a models folder existed when it was looking to get the projection from ras_proj. Why? It was possible to have invalid values folders or pathing in ras2fim.py and was creating issues on rare occasions (but it happened). Also changed date time to UTC.
     - `shared_validators.py`: text adjustment
     - `shared_variables.py`: add three new variables for S3.
     - `simplify_fim_rasters.py`: Change multi-proc / number of workers count as mentioned above.
     - `worker_fim_rasters.py`: Linting fix.
 - `tools`
     - `get_ras_models_by_catalog.py` renamed to `get_models_by_catalog.py`
     - `get_models_by_catalog.py:  renamed a page level function name. Changed to UTC time. Added "3_" as a new skip filter for downloading model folders. Removed code to validate incoming CRS value to use the `shared_validators.py` version.

### Testing

The new tool has a number of possibilities that can occur while uploading to S3, especially with attempting to keep only the latest version of a unit (huc and crs).  The s3 `output_ras2fim` should now keep only the latest editions that can be bundled up and given to HV or other teams as when needed by the `ras2release` tool coming later.

To setup the start of the test, I made unit folder from ras2fim.py with some models. I happened to have a full scale output set with all models for 12030105 with 22,000 files.  I used a full scale to also test multi-threading (not multi-proc), to check performance. Uploading and moving of folders in S3 take anywhere from 1 to 5 mins with a set of 22,000 files.

I made sure all tests pointed to our ras2fim-dev repo and NOT the production version of ras2fim.

My tests: (with each test I would download the `ras_output_tracker.csv` in the dev repo to ensure it added activity records correctly). The order of these tests I did was critical.

- `python ./tools/ras_unit_to_s3.py -s 12030105_2276_**230908** -b ras2fim-dev`  - First time upload of a unit with a huc-crs with a date of 230908.
- `python ./tools/ras_unit_to_s3.py -s 12030105_2276_**230908** -b ras2fim-dev` - Uploaded the same unit folder with same date which already exists now in S3, but selected to overwrite the existing one.
- `python ./tools/ras_unit_to_s3.py -s 12030105_2276_**230908** -b ras2fim-dev` - Uploaded the same unit folder with same date which already exists now in S3, but told it to archive the existing one (to the archive folder) and upload the new one to outputs.
- `python ./tools/ras_unit_to_s3.py -s 12030105_2276_**230915** -b ras2fim-dev` - Uploaded a unit with the same huc-crs but a newer date then what was already in S3. I told it to send the new incoming directly to archive. Opened up this option as the one in S3 may be older or newer then the incoming one.  That is possible if people load directly to S3 instead of using the tool and/or mistakes can happen.  Users can sort it out later if needed too.
- `python ./tools/ras_unit_to_s3.py -s 12030105_2276_**230915** -b ras2fim-dev` - Uploaded a unit with the same huc-crs but with the 230915 date. At this point, the 230908 is still there, so I told it to archive the old one and upload the new one.

The tool has the ability to see if two or more folders already exist in S3 outputs folder and the tool can handle this. To test it, I had the 230915 folder already in S3 by previous tests, but used aws cli to upload another folder (230904) directly into S3. Now I have two huc-crs folders in outputs which is invalid. Then I ran the tool attempting to upload yet a newer edition (230917). 
- `python ./tools/ras_unit_to_s3.py -s 12030105_2276_230917 -b ras2fim-dev`.  It advised me it would move both existing folders regardless of date into the archive folder and upload the new one. 

Every combination of using the new ras to s3 tool has an abort option which was also tested.

To help validate that a folder was uploaded correctly, I was constantly downloading the tracker file and viewing it, but I also used a tool in aws web console to get a folder count and folder size and ensure they match the source count and sizes. To do this, see the following image.

image

image

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Pre-commit executed and linting changes made.
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [ ] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### Merge Checklist (For Technical Lead use only)

- [x] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date

### CODE REVIEW

**Comment by AliForghani-NOAA** [comment]
Rob, 
looks very good and very user-friendly! The tool passed all my tests successfully as expected. Great work!

Two notes/questions:
1- The only thing in the command line messages that was not clear is in red boxes about tracker.csv file (i.e., there is no "ras_output_tracker.csv" file in my local output and the tool worked perfectly) 
image

2- Can you confirm that there is no need to download the "ras_output_tracker.csv" into the local output before using this tool?

**Comment by RobHanna-NOAA** [comment]
Hi Ali. Well the file does not need to be there ahead of time.  I needed to download it, update it, then push it back to S3.  Ya, I guess I don't need to tell the user that. I will update the message to say that the tracker file has been updated in S3 and not bother talking the local copy.  Good catch Ali. I will fix that in a minute.

**Comment by RobHanna-NOAA** [comment]
ok. Fixed.  :)

image

**Comment by AliForghani-NOAA** [comment]
Thanks Rob!

**Review by AliForghani-NOAA — DISMISSED** [review]

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
