### PR TITLE
[1pt] PR: Fixed some folder names and pathing

### LINKED ISSUE #258: [3pt] Fix 06 metric folder duplicate issues
In earlier versions, the code created and populated a folder called `06_metric`.  In principal the folder was replaced with a new folder called `06_src_depthgrids`. Some code starting from Step 7 and on, are still looking for the `06_metrics` folder. Fix this in code for Step 7 and higher.

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
Most the primary logic stages (Steps 1 to 6) are near completion. As we continue development on further modules, which rely on folder pathing from previous steps, folder names and pathing needed to be updates.  Step 6 in V1 was named "06_metric". For V2 up to this point, it was named `06_src_depthgrids`. This is now renamed to `06_create_rating_curves` to be more descriptive.  Various files were changed to make the folder names and flow match the code direction.

A decision was made to rename the related 06 code file name from `create_src_fimrasters_4fids.py` to `create_rating_curves.py`. 

Other misc fixes:
- Fixing a small handful of variable names to be more descriptive, intuitive and at least a bit more PEP-8 compliant.
- `create_shapes_from_hecras.py` was working but multi-proc logs was failing and not set up.
- `run_ras2rem.py` was removed as it is no longer relevant at this time. It exists in V1 branches if needed again.

Note: modules past Step 6 are still WIP but have more accurate folder names to help with mapping of data.

### Renamed Files

- `src`
    - `create_rating_curves.py`: renamed from `src/create_src_fimrasters_4fids.py`

### Changes 
- `src`
    - `calculate_all_terrain_stats.py`: Update some variable names and text; fix a folder creation timing and style; updated some text. (Note: still WIP)
    - `clip_dem_from_shape.py`: removed unnecessary output.
    - `conflate_hecras_to_nwm.py`: Added text to developers about how the `partial` python keyword works.
    - `create_fim_rasters.py`: Updated a bit of output.
    - `create_geocurves.py`: Updated for new Step 6 folder name variable. (Note: still WIP)
    - `create_rating_curves.py`: Updated for new Step 6 folder variable; file name updated to be more reflective of process. File name was `create_src_fimrasters_4fids.py`; updated some variable names.
    - `create_shapes_from_hecras.py`: It was showing errors due to incomplete setup of MP_LOG when running multi-proc. Multi-Proc has now been fully enabled. This required a new input variable to `fn_open_hecras` function.
    - `ras2fim.py`: Updates for the new file/function name from `create_rating_curves.py`; made some partial changes to setup processing flow from Step 6 (create rating curves) and farther. More changes will be made to code here as each module come online.
    - `ras2fim_logger.py`: minor console output change.
    - `reformat_ras_rating_curve.py`:  Updated for new Step 6 folder variable. (Note: still WIP)
    - `shared_variables.py`: Updates related to new step 6 folder name, create_rating_curves.py; also removed variable no longer needed from a module removed in previous releases.
    - `simplify_fim_rasters.py`:  Updated for new Step 6 folder name variable; small correction about how/when folders are created.  (Note: still WIP)
- `tools`
    - `hash_compare.py`: Update to sample text.

### Removals 
- `tools`
    - `run_ras2rem.py`

Closes Issue [258](https://github.com/NOAA-OWP/ras2fim/issues/258)

### Testing

- Testing was done to ensure ras2fim.py ran successfully from Steps 1 to 6, recognizing more bug fixes are coming soon.

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Pre-commit executed and linting changes made.
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep), except for a few minor additions which is generally allowed as long as they are not major changes.
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [ ] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/) - More variables have been cleaned up for PEP-8 but many more to come.
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date

### CODE REVIEW

**Comment by AliForghani-NOAA** [comment]
Hi Rob,
So far, I found two issues:
1- I made a new card #265 needed for Step 2 (conflation).
2- There is a new -u flag in "create_shapes_from_hecras.py" file that seems unnecessary, especially when we run this script on command line. Is there any specific reason we added this flag? To me, -o is all we need to specify the output folder.

**Comment by RobHanna-NOAA** [comment]
I forget why I added it but clearly don't need it anymore. I removed it.

**Comment by AliForghani-NOAA** [comment]
Another issue is in "create_geocurves.py" line 228, where the script expects HEC-RAS depth grids results in "05_hecras_output/Depth_Grid" folder, but "Depth_Grid" folder that is missing. However, I suggest not to fix this issue of "create_geocurves.py" in this PR. It may be more efficient to fix this after finalizing all works on Step5 and 6 and organizing the folder structure needed for "05_hecras_output" and "06_create_rating_curves" .

**Comment by RobHanna-NOAA** [comment]
Thank you Ali. We have more modules to do moving forward so not all, such as create_geocurves.py` have not yet been updated. So it is good for now.

**Review by AliForghani-NOAA — COMMENTED** [review]
Thanks Rob! I was able to run the code properly up to STEP 6.b (create rating curve stats). We can test the next steps after finalizing Steps 5 and 6.

**Comment by RobHanna-NOAA** [comment]
Perfect. Than I think we are good to approve. As 5 and 6 gets adjusted, we have better pathing and folder relationships. Which was part of the point of this PR. Get us in better folder patterns and help with the flow after step 6.

**Review by AliForghani-NOAA — DISMISSED** [review]

**Review by AliForghani-NOAA — DISMISSED** [review]
Thanks for the new fix.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
