### PR TITLE
[1pt] PR: Add ras2rem

### PR DESCRIPTION
**Pull request by AliForghani-NOAA**
Adding ras2rem as the new (optional) step for ras2fim
Issue: #30 

### Objective
For each NWM stream within the domain of HEC RAS models, `ras2fim` produces flood depth grids for a common set of reach averaged-depths.  `ras2rem` merges all these depth grids and create a single raster file delineating the areas inundated with different values of  reach averaged-depth. Plot below shows the raster file created by `ras2rem `(for illustration, the plot also shows dashed boxes with the extent of `ras2fim `results for four NWM streams used in this example):
image

### Additions  

Added the new `run_ras2rem.py` file containing two functions used for ras2rem

### Changes  

Updated `ras2fim.py` file with the changes required for addition of ras2rem

### Testing

Successfully ran the code with new changes on a Windows personal laptop. `ras2rem `is run using the optional `-m` flag and providing `y` (or any other word except "n") as argument as shown below:
python ras2fim.py -w 10170204 -i PathToHecRasModels -o PathToOutputs -p EPSG:26915 -v False -n PathToNationalDatasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" `-m y`

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [ ] Passes all unit tests locally (inside interactive Docker container, at `/foss_fim/`, run: `pytest unit_tests/`)
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/docs/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
@AliForghani-NOAA,

Here are some general feedback items to help align this PR with the general standards of our project:

- Please add a few more sentences describing what the enhancement does. What does `ras2rem` do? Add screenshots if applicable.
- Please make sure your PR title adheres to the standard i.e., "PR: Add ras2rem". For Pull Requests we add "PR:" to the beginning of the title
- It looks like you are wrapping entire bullets in the tick marks, when usually tick marks are reserved for script names. For example your first bullet in "Additions" should read: "Added the new `run_ras2rem.py` file containing two functions used for ras2rem". The same goes for the other bullets in the your description.
- You can delete the "Removals" section if nothing was removed
- Please update the CHANGELOG.md and document your changes. You can refer to the existing entry in the Changelog (v1.1.0) as well as the Inundation Mapping CHANGELOG for examples. Please make sure to reference the PR in the title for your version, too (refer to other examples).
- Please connect this PR to the `fim-development` project using the "Projects" option at the top right side of the PR.
- Please connect this PR to your issue #30 using the "Development" option at the top right side of the PR.
- Please add a Reviewer (top right side of PR). For this PR you can assign me, but I also recommend assigning Jim to review the actual code you've added.
- In your "Testing" section, can you supply example script usage so that others can easily try out the script on their systems?

**Comment by BradfordBates-NOAA** [comment]
Hey @AliForghani-NOAA can you please add more detail to the Changelog message? Your "Objective" paragraph could be the summary. And you'll need to add your "Changes" and "Additions" as well. Also please make sure you add the line break after your Changelog entry. You can see it after the other Changelog entry, with the "br" and "<>" characters. Also it looks like there is a trailing parenthetical in your title after the date.

I'm also seeing mixed case `ras2rem` and `Ras2rem` in your "Objective". Is that by design?

**Comment by AliForghani-NOAA** [comment]
> Hey @AliForghani-NOAA can you please add more detail to the Changelog message? Your "Objective" paragraph could be the summary. And you'll need to add your "Changes" and "Additions" as well. Also please make sure you add the line break after your Changelog entry. You can see it after the other Changelog entry, with the "br" and "<>" characters. Also it looks like there is a trailing parenthetical in your title after the date.
> 
> I'm also seeing mixed case `ras2rem` and `Ras2rem` in your "Objective". Is that by design?
 
Hi @BradfordBates-NOAA 
Thanks for the notes. I updated the Changelog based on your new notes, including removing the inconsistency in referring to ras2rem (ras2rem vs Ras2rem)

**Review by BradfordBates-NOAA — DISMISSED** [review]

**Comment by BradfordBates-NOAA** [comment]
I have approved but recommend @JamesColl-NOAA also review

**Review by JamesColl-NOAA — CHANGES_REQUESTED** [review]
Per conversations and AWS scaffolding last week I have tweaked the following:
* RAS2REM is an optional flag we default to true.  I've tweaked that behavior, and more explicitly named and parameterized that variable with the appropriate decorative.
* We should avoid co-opting that -t flag, I made that -m.

I'll let you try running this version to make sure I didn't break how you were using this, and let you approve.

**Review by JamesColl-NOAA — COMMENTED** [review]
Cleaning up my errant comments

**Review by JamesColl-NOAA — APPROVED** [review]
Great Job!

**Pull request merged**
