### PR TITLE
[1pt] PR: stop the code if there is no conflated model

### PR DESCRIPTION
**Pull request by AliForghani-NOAA**
### Summary 
This PR will check the result of conflation step (step 2) and will stop the code if no conflated model exists.
This PR addresses issues #47 

This PR does not fully address #82 . The issue #82 requests handling all sorts of input errors (such as run arguments or provided models). This PR only addresses the cases of #82 in which all arguments and models are correct and consistent, but no HEC-RAS model is conflated into NWM reaches of the given HUC8. 

### Background
Ras2fim needs at least one conflated model (one HEC-RAS model that its cross sections intersect with NWM reaches).  If none of the user provided HEC-RAS models conflates to NWM reaches in the given HUC8, then the code should inform the user and terminate. 

The file "***_stream_qc.csv" in folder '02_shapes_from_conflation' is the best place to check for this situation. This file should contain at least one record (one conflated model). During Step 5, ras2fim reads this file to start making sub HEC-RAS models. 

### Changes  
- `src/conflate_hecras_to_nwm.py` 
&emsp;&emsp; called the "errors.check_conflated_models_count()" function to check the number of records in the  "***_stream_qc.csv" file.

- `src/errors.py` 
&emsp;&emsp; Added the definition of "errors.check_conflated_models_count()" function.

### Testing
Successfully (with an instructive error message) stopped the code if no conflated model exists. 

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
Sorry that I was unable to get back to this earlier Ali.  Issue #82 talks about an error that gives us `ValueError: Cannot write empty DataFrame to file.`  There are at least one way to trigger it which is having invalid models in the original input models folder. It is easy mistake to make and when the error occurs, it is very unclear. At a minimum, we need to handle this error with a more descriptive error, but better yet.. the code should know "why" it failed, which could be more than one way.  We know of one way it can fail, but we need to research and add code to figure out other permutations of why it could fail and put up an appropriate error message.

**Comment by AliForghani-NOAA** [comment]
Rob,
Regarding "the code should know "why" it failed", this PR's goal is NOT to answer this question. You can have another PR to answer that. 
The goal of this PR is just to stop the code when there is ZERO conflated models for ras2fim to process, so the user won't see that random error you are referring to (`ValueError: Cannot write empty DataFrame to file`)  
I do not see any needed change on the PR.

**Comment by AliForghani-NOAA** [comment]
I think there is a conceptual misunderstanding of this PR. We will need to discuss this offline.

**Comment by RobHanna-NOAA** [comment]
ok. Can you tell me how I can test for this PR? (without having to manually change or edit any files from the 01 to 05 directories?  I just put in non valid model files in the "models" folder, which was the fix I was hoping for.  But.. as you mentioned.. you interpret #82 as a different problem. No problem. maybe  tell me how to replicate the problem and test the fix and we can move forward :)

**Comment by AliForghani-NOAA** [comment]
You can test your previous failed run as you were doing before, and let's see what happens.

**Comment by AliForghani-NOAA** [comment]
As a summary, this PR does not fully address issue #82, so this PR will not close #82. The issue #82 requests handling all sorts of input errors (such as run arguments or provided models). This PR only addresses the cases of #82 in which all arguments and models are correct and consistent, but no HEC-RAS model is conflated into NWM reaches of the given HUC8.

**Comment by AliForghani-NOAA** [comment]
@RobHanna-NOAA 
Below is how I was testing the PR. My "modelsFolder" has a single HEc_RAS model called "5791800_CLEAR 177_g01_1678771301"

python ras2fim.py -w 12090301 -i modelsFolder -o NoConflateTestOutput -p EPSG:2277 -mc C:/Users/rdp-user/Desktop/runFolder/models/OWP_ras_models_catalog_12090301.csv -t C:\Users\rdp-user\Desktop\runFolder\12090301_dem_meters_0_2277.tif

Running above, get this error message:
image

**Review by RobHanna-NOAA — DISMISSED** [review]

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
