### PR TITLE
[1pt] PR: Create inundation process for ras2fim

### PR DESCRIPTION
**Pull request by LauraKeys-NOAA**
This pull request includes additions and modifications to the existing ras2fim / ras2rem workflow that creates output files that can be fed directly into inundation.py.

### Additions  
- `ras2catchments.py`: creates COMID catchments as a raster (tif) and polygons (gpkg) for use with discharge / stage lookup. The inputs to the main function are input and output directories (input: location of step 5 ras2fim files where all the depth grid files live, output: location of ras2rem files [or anywhere else of user's choosing, if they don't want the resulting COMID raster and polygon files to be with the ras2rem outputs])
-  `ras2inundation.py`: copy of inundation.py script that can be modified for ras2fim as necessary if separate needs arise from HAND-based modeling

### Changes  
- `ras2rem.py`: Modifications to synthetic rating curve (SRC) generation to ensure we have the necessary fields for inundation.py to work, consistent with HAND-based hydro tables. Specifically adds or modifies the following columns:
    - HydroID (added as copy of feature_id)
    - HUC (added)
    - LakeID (added as -999)
    - last_updated (added as empty string)
    - submitter (added as empty string)
    - obs_source (added as empty string)
    - AvgDepth (m) renamed to stage
    - Flow (cms) renamed to discharge_cms

### Removals 
- none

### Testing
- Tested on Windows GFE for 3 different sets of ras2fim models from the Iowa Flood Center. The ras2rem script runs without error, and the inundation process works without error.

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Project documentation has been updated ([CHANGELOG](/docs/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Comment by LauraKeys-NOAA** [comment]
Also satisfies issue #38 to export catchment boundaries as polygons, since it's a necessary input to the inundation script

**Comment by BradfordBates-NOAA** [comment]
@LauraKeys-NOAA Please merge with `dev` and update Changelog with PR (42) number instead of original Issue number (29). Version number can be 1.3.0.

**Comment by BradfordBates-NOAA** [comment]
@LauraKeys-NOAA your points for the PR should usually be 1 pt. The points are captured by the issue that the PR resolves, in your case #29. Also, please connect #29 to this PR using the "Development" setting option at the upper right of the PR interface.

**Comment by LauraKeys-NOAA** [comment]
Sorry, I didn't usually add the points to the PRs in the inundation-mapping
repo, just left that to Rob H. Will change those.

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
