### PR TITLE
[1pt] PR: V1 - fix a bug in ras2inundation and remove making gpkg files in create_geocurves.py

### LINKED ISSUE #228: [8pt] V1 - Bug in ras2inundation.py
Ras2inundation.py cannot produce inundation outputs because of a bug where the extent geopackages do not get produced. We want to change the functionality to use the 'geometry' column of the geocurves and eliminate the reliance on the geopackages.

### PR DESCRIPTION
**Pull request by AliForghani-NOAA**
This PR solves issue #228 and performs:

1. Removes the option of making gpkg files in `create_geocurves.py`. The geometry info is only saved in 'geometry' column of geocurves csv files.
2. Fixes a bug in `ras2inundation.py` to make sure all geometry info can be read from 'geometry' column of geocurves csv files. Also, because geocurve gpkg polygon files are not available anymore as the input, `ras2inundation.py` now reads ras2fim version number and `stage_m` value (corresponding to the `discharge_cms`) from geocurve csv files. Also, removed the "overwrite" flag argument for this file. 
3. Improved the performance of `ras2inundation.py` (e.g., by vectorizing a for loop)

### Changes  

- `create_geocurves.py` ... see above
- `ras2inundation.py`  ... see above
- `config/r2f_config.env`  ... removed the PRODUCE_GEOCURVE_POLYGONS flag
- `src/ras2fim.py` ... adjusted/removed the arguments used to call "create_geocurve.py" from ras2fim.py

### Testing
The test, running `create_geocurves.py`  followed by running `ras2inundation.py`, was performed successfully on rel_101. These two runs produce 1) 770 geocurves csv files and 2) a gpkg file with 770 records.  

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Pre-commit executed and linting changes made.
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### Merge Checklist (For Technical Lead use only)

- [x] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date

### CODE REVIEW

**Comment by RobHanna-NOAA** [comment]
Hi Ali. I did a quick peak at the code and it looks good. I will look at it deeper in a few days and test it out.  One recommendation for an update on both of the inundation PR, is to add a RLOG.trace line inside of the `for feature_id in feature_id_polygon_path_dict:`  You can put a message something like f"processing gdf dataframe for {featureid}". RLOG.trace goes to the logs only and not the screen, but if something blows up in the interator, we have an idea what where it was while processing that set.

**Comment by RobHanna-NOAA** [comment]
I looked into the error for `RLOG.warning(f"depth_grid of {depth_grid} does not have any heights above surfase.")`.  This V1 edition did not have multi-proc logging in it and the error is from that line attempting to write to a RLOG file inside multi-proc that doesn't work. For V1, let's just change that from a RLOG.warning to a print.

**Comment by AliForghani-NOAA** [comment]
Thanks Rob for the comments. As you said, for V1, I will just change the RLOG.warning line to a print. Also, will add more logging info into the codes.

**Comment by RobHanna-NOAA** [comment]
After talking to Carson about a few misc topics, we talked about ras2inundation.py.  He would like two minor more changes to V1 (and V2). Remove the -o overwrite flag from ras2inundation.py and also added a quick test to ensure the incoming target file name (-t) ends in .gkpg. (please. :) )

**Comment by RobHanna-NOAA** [comment]
Note: The version system, and output column for it, is broken and adds the value of "docs/CHANGELOG.md". We will not fix in in V1 or V2, but a new card will be created to fix it in V2 only.

**Comment by AliForghani-NOAA** [comment]
Rob, for this PR, which is only for V1, I removed the overwrite flag. Also, I added code to check the extension of output to be .gpkg. This PR is now ready to retest. 

Getting the version number is correct for V2, and as you said, there is no attempt to fix that in V1.

**Review by RobHanna-NOAA — APPROVED** [review]
Nice Work Ali.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
