### PR TITLE
[5pt] PR: standardize Simplified Depth Grids and ras2rem outputs

### PR DESCRIPTION
**Pull request by AliForghani-NOAA**
### Summary 
By this PR:
1. The results of `simplify_fim_rasters.py` is now saved in output folder `06_metric/Depth_Grid`. Also, if HEC-RAS models units are in feet:
    - Pixel values of the simplified depth grids (z unit) are converted into meter. 
    - File names of resulting depth grids (like "featureid-remvalue.tif") are updated with rem values in meter. 

2. The results of `run_ras2rem.py` is now saved in output folder `06_metric/ras2rem` in which:
    - Rating curve values are in meter and m^3/s
    - `rem.tif` file has projection of EPSG:5070 and pixel values (z unit) are in meter. 

Note that this PR is not addressing standardization for the results of step 9 ( `make_catchments` function), and @RobHanna-NOAA will work on that section, if needed. 

### Background
It is possible that one HUC8 has HEC-RAS models containing multiple projections. Therefore, we might need to have separate ras2fim runs for each EPSG/CRS for a single HUC8. This causes confusion, especially when the two sets of HEC-RAS models are in different units of meter and feet. This PR will standardize ras2fim outputs such that, for all ras2fim runs, an output folder `06_metric` containing results only in meter with EPSG:5070 is created. 

### Changes  
- `src/ras2fim.py` : Passed "model_unit" argument into `fn_simplify_fim_rasters` and `fn_run_ras2rem` functions, so these functions can convert the results into metric when HEC-RAS models unit are in feet.

- `src/simplify_fim_rasters.py` 
  1. The results of this step is now saved in output folder `06_metric/Depth_Grid` 
  2. If model unit is in feet, pixel values of the simplified depth grids (z unit) are converted into meter and file names of resulting depth grids (like "featureid-remvalue.tif") are updated with rem values in meter. 

- `src/run_ras2rem.py` :
  1. The results of ras2rem is now saved in output folder `06_metric/ras2rem`.
  2. If model unit is in feet, rating curve values are converted into meter and rounded into 3 digits. 

- `src/shared_variables.py` 
  1. Changed the CRS of the standardized outputs to be EPSG:5070. 

- `src/shared_functions.py` 
  1. Added a new function called `find_model_unit_from_rating_curves` to get 'model_unit' of HEC-RAS models, if we already have rating curve results from a successful run of ras2fim for step 5 (`fn_create_fim_rasters` function). This is applicable only when a user wants to directly run  `simplify_fim_rasters.py` or `run_ras2rem.py`. 

- `src/ras2catchments.py` : Changed pathing for location of the new depth grids.

### Testing
Successfully rerun HUC 12090301 (to the end of step 8 --run_ras2rem.py) with below arguments: 
python ras2fim.py -w 12090301 -i Models -o Outputs -p EPSG:2277 -mc C:/Users/rdp-user/Desktop/runFolder/models/OWP_ras_models_catalog_12090301.csv -t 12090301_dem_meters_0_2277.tif

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [ ] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### CODE REVIEW

**Review by LauraKeys-NOAA — COMMENTED** [review]
The conversion logic all looks reasonable to me.

**Comment by EmilyDeardorff** [comment]
I ran `ras2fim.py` (including Rob's 7/26 contribution) on a small subset of the 12090301 HUC with the following command: 


```python ras2fim.py -w 12090301 -i C:\ras2fim_data\temp\00_hecras_inputs_small_testing_subset -o C:\ras2fim_data\output_ras2fim_models\12090301_meters_2277_smalltest1 -p EPSG:2277 -t C:\ras2fim_data\inputs\12090301_dem_meters_0_2277.tif ```

This code ran up until the end midway through code step 9, where it errored out with the following message:

```Getting list of feature IDs
Traceback (most recent call last):
  File "ras2fim.py", line 597, in <module>
    init_and_run_ras2fim(**args)
  File "ras2fim.py", line 459, in init_and_run_ras2fim
    fn_run_ras2fim(str_huc8_arg,
  File "ras2fim.py", line 285, in fn_run_ras2fim
    make_catchments(str_huc8_arg, str_out_arg, str_nation_arg, model_huc_catalog_path)
  File "C:\Users\rdp-user\projects\dev-standardize-outputs\ras2fim\src\ras2catchments.py", line 384, in make_catchments
    raise Exception("No depth grid tif's found. Please ensure that ras2fim has been run and the 05_hecras_output" \
Exception: No depth grid tif's found. Please ensure that ras2fim has been run and the 05_hecras_output has depth grid tifs in the pattern of {featureID-{depth value}.tif. ie) 5789848-18.tif
(ras2fim) PS C:\Users\rdp-user\projects\dev-standardize-outputs\ras2fim\src>```

I am not sure if this error has to do with how I ran the code or a bug in the branch. I will test with other commands and await feedback on this error.

**Comment by RobHanna-NOAA** [comment]
Ya. sorry for the delay. That is exactly what I am fixing so we can keep this build clean. A separate PR will likely remove/comment it, but I think it is important to get it work in the meantime.  (for archiving)

**Review by EmilyDeardorff — DISMISSED** [review]
I tested this PR on 12090301 and 12040101. `ras2fim.py` successfully ran all the way to the end and the outputs had the expected units, folder structure, and projection.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
