### PR TITLE
[3pt] PR: new ras2release tool

### LINKED ISSUE #80: [21pt] Build ras2release
Take in a set of HUC ras2fim output folders and extract key files that need to go HydroVis. We can also have it run Emily's rating curve adjustments as part of this process.

It will need it's own versioning system. First drafts done by hand have started with "Rel 100"  (as in Release 100), then "Rel 101", etc.  Skipping the "v" will remove some confusion of getting mixed up with code versions.

- Dec 7, 2023
    - New requirement: no longer aggregate the two "reformat" / ras2calibration files, but keep them split per unit (huc / crs). Just copy them over from each unit output folder.

### PR DESCRIPTION
**Pull request by RobHanna-NOAA**
This is a new tool that can take all applicable output unit files from S3, organize them, and create deployments for both FIM and HydroVIS.  It can pull all units from the S3 outputs folder, or provided specific unit names to be included in the release.

Other misc changes
- Some shared functions were renamed in light of new uses
- Various linting changes (not all previous files were linted correctly)
- Changes to how s3_shared_functions for downloading folders and files to how it handles multi-threading. It can now detect if there are lots of incoming folders (more than 100) and give it priority for multi-threading priority. If the number of folders incoming is low, it gives priority of multi-threading to actual downloading of file. While this will not meet all conditions, it flows better for when downloading models, which have multi hundreds of small folder, versus downloading unit output folders which don't have many folders to download, but lots of files inside each folder. This triggered updates to most of the s3* tools.
- Some files now have a message added at the top of them about adding a new variable in the near future and keep it consistent across those files.

__Note__ : Developed at this time against V1 folder pathing. It can be quickly changed as V2 pathing is completed. Also. Not functionality is embedded into this tool such as FIM deployment files (via reformat_rating_curves.py) and possibly others.

### Additions  

- `tools`
    - `ras2release.py`: New tools
   
### Changes  

- `gitignore` - update to ensure lst files are uploaded correctly to git
- `src`
     - `conflate_hecras_to_nwm.py`, `create_fim_rasters.py`, `ras2fim.py`, `shared_functions.py`:  changes to reflect shared function name change.
     - `reformat_ras_rating_curves.py`: Pre-emptive changes anticipating changings coming soon for V2.
     - `shared_variables.py`: Added new variables.
 - `tools`
     - `acquire_and_preprocess_3dep_dems.py`, `extend_huc8_domain.py`, `s3_model_mgmt.py`:  changes to reflect shared function name change.
     - `evalute_ras2fim_models.py`, `s3_batch_evalations.py`: Linting fixes
     - `ras2inundation.py`: a few linting fixes, but fixed a small bug not previously discovered. A few variables were renamed.
     - `s3_get_models.py`: Updates for adjusted shared functions name changes, changed to the new s3 download_folders function usage.
     - `s3_search_tool.py`: Updates for adjusted shared functions name changes, plus a few text and variable names updates.
     - `s3_shared_functions.py`:  A rebuild of how folders and files are downloaded to make better use of multi-threading and add flexibility to work with the new ras2release tool as well as other scripts coming soon.

### Testing

- Dev testing done:
    - multiple combinations of arguments and conditions for `ras2release.py`. Testing done against both ras2fim and ras2fim-dev buckets.
    - Re-tested a number of other tools to ensure they are still fine such as `ras2fim.py`, `ras_unit_to_s3.py`, s3_get_models.py`, s3_model_mgmt.py`, and `s3_search_tools.py`
    - Tested against all units in s3 outputs plus a defined set of units.. e.g. python .\tools\ras2release.py -r 121-test-few -ss -u "12040101_102739_ble_230922" "120301062276_ble_230926"
    

- Recommended review testing:  random combinations of ras2release against ras2fim-dev watching for correct downloading to the local ras2release folder as well sub folders, and creating of the HydroVIS.

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Pre-commit executed and linting changes made.
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [ ] n/a - Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### Merge Checklist (For Technical Lead use only)

- [ ] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date

### CODE REVIEW

**Comment by EmilyDeardorff** [comment]
I ran a few test examples and ran into some errors with the S3 url. I've included them below. 

**Commands I ran:**
`python .\tools\ras2release.py -r r121 -w C:\Users\rdp-user\projects\ras2release\release_folders -s s3:\\ras2fim-dev\temp\emily\ -ss`

`python .\tools\ras2release.py -r r121 -w C:\Users\rdp-user\projects\ras2release\release_folders -s s3:\\ras2fim-dev\temp\emily\ -t s3:\\ras2fim-dev\temp\emily\ras2release\ -ss`

**Errors I got:**

image
image

**Comment by EmilyDeardorff** [comment]
I've run into another situation that might just be user error, but I got this error:

The code I ran: 
`(ras2fim) PS C:\Users\rdp-user\projects\ras2release\ras2fim> python .\tools\ras2release.py -r 121 -w C:Users\rdp-user\projects\ras2release\release_folders -s s3:\\ras2fim-dev\temp\emily -ss`

The error:
`2024-02-09 00:55:43 <CRITICAL> : Traceback (most recent call last):
  File ".\tools\ras2release.py", line 524, in <module>
    RLOG.setup(os.path.join(log_file_folder, log_file_name))
  File "C:\Users\rdp-user\projects\ras2release\ras2fim\src\ras2fim_logger.py", line 94, in setup
    os.mkdir(folder_path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:Users\\rdp-user\\projects\\ras2release\\release_folders\\logs'
******  Logging to the file system not yet setup.`

**Comment by EmilyDeardorff** [comment]
Here's the info from the error log file from that last run: 

```
(base) PS C:\Users\rdp-user\projects\ras2release\release_folders\logs> cat .\ras2release_240208_182034136556_errors.log
2024-02-08 18:20:34 | CRITICAL || Traceback (most recent call last):
  File ".\tools\ras2release.py", line 524, in <module>
    create_ras2release(**args)
  File ".\tools\ras2release.py", line 71, in create_ras2release
    rd = __validate_input(
  File ".\tools\ras2release.py", line 393, in __validate_input
    if s3_sf.is_valid_s3_folder(s3_path_to_output_folder) is False:
  File "C:\Users\rdp-user\projects\ras2release\ras2fim\tools\s3_shared_functions.py", line 925, in is_valid_s3_folder
    if does_s3_bucket_exist(bucket_name) is False:
  File "C:\Users\rdp-user\projects\ras2release\ras2fim\tools\s3_shared_functions.py", line 1002, in does_s3_bucket_exist
    client.head_bucket(Bucket=bucket_name)
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\client.py", line 878, in _make_api_call
    request_dict = self._convert_to_request_dict(
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\client.py", line 936, in _convert_to_request_dict
    api_params = self._emit_api_params(
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\client.py", line 969, in _emit_api_params
    self.meta.events.emit(
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\Users\rdp-user\.conda\envs\ras2fim\lib\site-packages\botocore\handlers.py", line 275, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "s3:\\ras2fim-dev\temp\emily\": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"```

**Comment by EmilyDeardorff** [comment]
I pulled down the recent updates and ran the following: 
`python .\tools\ras2release.py -r r121 -w C:\Users\rdp-user\projects\ras2release\release_folders -s s3:\\ras2fim-dev\temp\emily\ -ss`

I got this error: 
`2024-02-13 19:55:28 <CRITICAL> : No output unit folders were found at temp/emily`

Do you think this is a problem with how I've set it up? Or an issue with the tool?

**Comment by RobHanna-NOAA** [comment]
HI Emily.  Yes. The error is correct. There are no unit output folder there.  aka.  It is looking for at least one standard output folder of unitname_version  (ie. 12090301_2277_ble_231213) or somethign like that.

**Review by EmilyDeardorff — DISMISSED** [review]
During my meeting with Rob today I realized that the way I was setting up my pathing in the run command was not quite right. I tested two command formats using more of the default paths and ras2release worked as expected. There is some functionality that isn't finished (i.e. ras2calibration and the upload to S3) but the rest of the function worked as expected.

Commands I ran:   

`python ./tools/ras2release.py -r emily_test1`

`python ./tools/ras2release.py -r emily_test2 -u "12090301_2277_ble_230923" "12030101_2276_ble_230925"`

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
