### PR TITLE
[2pt] PR: Add GVAL functionality to ras2fim codebase

### LINKED ISSUE #200: [21pt] Add GVAL functionality to ras2fim codebase

### PR DESCRIPTION
**Pull request by GregoryPetrochenkov-NOAA**
This pull requests integrates gval in to the codebase allowing evaluations of model performance to take place (addressing #200 ).  The added modules will be incorporated in to the future ras2fim pipeline.

### Additions  
- `tools`
    - `evaluate_ra2fim_model.py`: Method for using gval to run an evaluation of model performance
    - `s3_batch_evluation.py`:  Module to facilitate batch processing evaluations using s3

### Changes  
- `tools`
    - `ras2inundation.py`: Changes to formatting

### Testing
- Command line testing of all arguments for both added modules

### Checklist

_You may update this checklist before and/or after creating the PR. If you're unsure about any of them, please ask, we're here to help! These items are what we are going to look for before merging your code._

- [x] Informative and human-readable title, using the format: `[_pt] PR: <description>`
- [x] Pre-commit executed and linting changes made.
- [x] Links are provided if this PR resolves an issue, or depends on another other PR
- [x] If submitting a PR to the `dev` branch (the default branch), you have a descriptive [Feature Branch](https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow) name using the format: `dev-<description-of-change>` (e.g.: `dev-revise-levee-masking`)
- [x] Changes are limited to a single goal (no scope creep)
- [x] The feature branch you're submitting as a PR is up to date (merged) with the latest `dev` branch
- [x] Changes adhere to [PEP-8 Style Guidelines](https://peps.python.org/pep-0008/)
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated ([CHANGELOG](/doc/CHANGELOG.md) and/or [README](/README.md))
- [x] [Reviewers requested](https://help.github.com/articles/requesting-a-pull-request-review/)

### Merge Checklist (For Technical Lead use only)

- [x] Update [CHANGELOG](/docs/CHANGELOG.md) with latest version number and merge date

### CODE REVIEW

**Comment by AliForghani-NOAA** [comment]
Hi Greg, 
This looks great. I successfully run the tools using the suggested paths. I have some small suggestions:
1- Currently there is no logging appearing on the screen while running the `evaluate_ra2fim_model.py` code. Can you please add very basic logging like "working on blah..." so the user knows the code is running. 
2- In `'s3_batch_evaluation.py'` test run, I specified `-b "ble,nws"` and I see results only for ble and there is no results for nws because there is no benchmark data available on S3 for nws, correct? If yes, I think it makes sense to report this at least on the screen so user knows why there is no result for nws.  The same issue for -st flag arguments, as well.  
3- I found the 'spatial_unit' a little confusing for describing -st flag. Do you think it make sense to revise this and change the help text of the -st flag, so user knows it is simply the tag name used to refer to a ras2fim run? 


@RobHanna-NOAA These new tools require new python packages (geocube, gval and its dependencies) that should be incorporated into ras2fim env file. Ideally, we need to update the `environment.yml` file as part of the updated files for this PR. Do you think we should approve this PR as is or wait until you update the `environment.yml` file?

**Comment by RobHanna-NOAA** [comment]
oh. new packages huh. Ok. yes, we need to update the environment file and retest ras2fim.py and should re-test get_models_by_catalog.py.  Do you guys know how to update the environment file. There is a section in the ras2fim AWS Dev User Guide that talks about how to do it.  Give it a try and adjust accordingly.  https://docs.google.com/document/d/1mRUFmEsYqzwwURgeWfc3CRdneAVn9_saWyEZDGXu-GM/edit#heading=h.8nkkt2kvxrjm

**Comment by RobHanna-NOAA** [comment]
I also notice a few other tidbits that I missed earlier:
1) some inputs in "__main__" that should not be there but up at the top of the page. Make sure you do an isort on it after that fix. 
2) Never put any logic in the __main__. There are some splits in there that should be up in the main logic.  There is a argparser type , I think it is called nargs (ie. type=nargs) or something that ensure it comes out of the args as a list.  I have had trouble with it comign in as a string when there is only one, but if you let it come through into the run_batch_elevations, you can check and fix it there. Yes.. it is good that it is a list (even if it is only one element) that goes through the logic. Why never have logic in _ _main_ __?  Other scripts may call this script directly and not through command line. I already have  plans to do that when I add this to ras2fim_unit_pipeline.py (coming). 
3) Generally we should starting adding child validation functions to ensure you get the incomign data you expect. Slowly we aer adding more and more of them. I let it slide when I first saw this, but keep it in mind as we make / adjust other code. You have to assume that all inputs could be wrong coming into your main function (ie_run_batch_evaluations. We have lots of examples. If you don't do it on this one, that is fine, unless you feel ambitious. See some of my "s3_xxx" file examples and if you see a better way to do it, feel free to implement a better pattern. :)

**Comment by RobHanna-NOAA** [comment]
Dang.. sorry.. another one. We need a try catch in the __main__. See s3_search_tool.py folder for examples. Why? When this gets put into AWS, it won't log the errors to our logging system if we let the try/except not get caught by the code. If the console has to catch any exceptions, then AWS logs it in a deep logging part of their logging system which is hard to find. Also.. with any try / except, know exactly why it was caught. ie) Add traceback.format_exc(). When you just use exception as ex, then go print(ex), you get the message only and not the stack trace, unless it is caught by the console. Hence.. all of my code  uses traceback.format_exc().

You can also add RLOG.trace so you have an idea of exactly what records in a for loop was being worked on when it blew up. Make sure when you log it, you have some sort of identifier such as what for loop and what value was being used when it broke. 

Also. if you put for loop in order, it makes it even easier to find problems. Always build to the worst case scenario and not the happy path to make stronger code. The hardest part of coding is if something broke and you have no idea where, when and what data was creating the problem. RLOG.trace goes to the log files only. You can also use some RLOG.lprint if you want to help uses it as a bit of a progress status for users if you like. Helps them see how things are progress.

Sorry to be more picky now. Now that was thinkign more about it, maybe we can clean up some of these tidbits now. Creating better patterns especially since "RayT" is going to be seeing our code and we want it to look strong and robust.

**Comment by GregoryPetrochenkov-NOAA** [comment]
I went ahead and addressed the changes that were requested.  When you have a chance please review the changes and let me know if any more revisions are necessary.  Thanks.

**Review by AliForghani-NOAA — DISMISSED** [review]
@GregoryPetrochenkov-NOAA Thanks Greg for updating the PR with requested changes. I retested the new environment as well as the two tools and all work fine.

**Review by RobHanna-NOAA — DISMISSED** [review]
I add tons of comments earlier and Greg..  you are a super star for implementing it all. I did a quick ras2fim test to make sure the environment file was still happy and it was just fine. Sounds like Ali did the test on your tools directly, so we are all good. Stellar Job.

**Review by CarsonPruitt-NOAA — APPROVED** [review]

**Pull request merged**
