### PR TITLE
[2pt] PR: Bundle of QOL and bugfix updates

### PR DESCRIPTION
**Pull request by JamesColl-NOAA**
Addressed #14 (in part) here: I'm sure there are more elegant ways to do this, but in essence we: 
* wait for a few seconds to let things settle out
* test the file size to see if any data was returned
* While the amount of data returned is less than 10Kb, wipe the tile and retry the download
* If we attempt it more than 10 times, print a small error and continue trying to run
* Retry the HUC from step 3 (e.g: `python ras2fim.py -w 07080201 -i <PATH>\Iowa_Flood_Center\unpacked\07080201 -o <PATH>\outputs\07080201 -p EPSG:26915 -v True -n B<PATH>\national-datasets -r "C:\Program Files (x86)\HEC\HEC-RAS\6.0" -s "3"`)

Changes in _get_usgs_dem_from_shape_
```
# Quick/crappy file size check to ensure something was actually returned
    time.sleep(15)
    i = 0
    fs = os.path.getsize(list_tile_url[1]) # returns in bytes
    fs = fs / 1000                         # transform to kb
    
    while (fs < 10):
        os.remove(list_tile_url[1])
        urllib.request.urlretrieve(list_tile_url[0], list_tile_url[1])
        time.sleep(15)
        i = i + 1
        fs = os.path.getsize(list_tile_url[1]) # returns in bytes
        fs = fs / 1000                         # transform to kb
        if i == 10:
            print(" -- ALERT: DEM download failed --")
            break
```

### CODE REVIEW

**Comment by BradfordBates-NOAA** [comment]
@JamesColl-NOAA Which issue does this PR resolve?

**Comment by BradfordBates-NOAA** [comment]
@JamesColl-NOAA Please merge this with the latest `dev`

**Comment by BrianAvant-NOAA** [comment]
@JamesColl-NOAA send me that url when you get a chance

**Comment by JamesColl-NOAA** [comment]
See original issue #14 , the joys of intermittent bug hunting.

**Comment by BradfordBates-NOAA** [comment]
@JamesColl-NOAA does the `dev-dem-update` branch contain fixes for more than just the DEM download error? From your comment, if seems like it's also doing projection checks and unit checks.

**Review by BrianAvant-NOAA — COMMENTED** [review]
I didn't run any tests but Jim and I walked through his updates and I didn't see anything out of the ordinary with the changes.

**Review by BradfordBates-NOAA — APPROVED** [review]

**Pull request merged**
